//+------------------------------------------------------------------+
//|                                               PA-SNIPER-GLOD.mq5 |
//|                                       Generated by Gemini AI     |
//+------------------------------------------------------------------+
#property copyright "Your Name"
#property link      "https://yourwebsite.com"
#property version   "2.20"

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\SymbolInfo.mqh>

CTrade         trade;
CPositionInfo  m_position;
CSymbolInfo    m_symbol;

//--- [1] SECURITY & LIMITS ---
const datetime InpExpiryDate = D'2027.12.30 23:59:59'; // วันหมดอายุ
long AllowedAccounts[] = {0};                  // ใส่เลขพอร์ตเพื่อล็อค (รองรับหลายพอร์ต) หรือ ใส่ 0 เพื่อให้ใช้ได้ทุกพอร์ต
input int      InpMaxServerReq   = 30000;              // ลิมิตส่งคำสั่งเข้า Server ต่อวัน (กันโบรกแบน)

//--- [2] STRATEGY & MONEY MANAGEMENT ---
input double   InpLotStart       = 0.05;       // Start Lot
input double   InpMultiplier     = 1.5;         // Lot Multiplier
input int      InpMaxOrders      = 1000;        // Max Orders
input double   InpMaxDDPercent   = 15.0;        // Cut Loss (%)

//--- [3] ENTRY & GRID STEP ---
input bool     InpUseATRGrid     = true;        // เปิดใช้ ATR Dynamic Grid (True=ATR, False=Pip Step)
input int      InpPipStep        = 440;         // Pip Step (point) [หากไม่ใช้ ATR]
input double   InpATR_Mult       = 3.0;         // ATR Multiplier [หากใช้ ATR]
input int      InpMinStep        = 440;         // Min Step Points [หากใช้ ATR]
input int      InpMaxStep        = 1000;        // Max Step Points [หากใช้ ATR]

//--- [4] EXIT & PROFIT LOCK ---
input bool     InpSoftClose      = false;       // โหมด Soft Close (รวบกำไรไม้ค้างแล้วหยุด ไม่เปิดไม้ใหม่)
input double   InpTargetUSD      = 0.0;         // Target Profit (USD) [0 = ไม่ใช้งาน]
input int      InpTPAverage      = 100;         // Take Profit Average (point) [0 = ไม่ใช้งาน]
input double   InpTrailingStart  = 0.0;         // Trailing Start ($) [0 = ไม่ใช้งาน]
input double   InpTrailingStop   = 0.0;         // Trailing Stop ($)

//--- [5] DAILY TARGETS ---
input double   InpDailyProfit    = 0.0;         // Daily Profit Target ($) [0 = ไม่ใช้งาน]
input double   InpDailyLoss      = 0.0;         // Daily Loss Limit ($) [0 = ไม่ใช้งาน]

//--- [6] TIME FILTER SESSION ---
input bool     InpUseTimeFilter  = false;       // เปิดใช้งานระบบแบ่งเวลาเทรด
input bool     InpUseSession1    = false;       // เปิดใช้งาน Session 1
input string   InpStart1         = "03:00";     // Start Time 1 (HH:MM)
input string   InpStop1          = "06:00";     // Stop Time 1 (HH:MM)
input bool     InpUseSession2    = false;       // เปิดใช้งาน Session 2
input string   InpStart2         = "11:00";     // Start Time 2 (HH:MM)
input string   InpStop2          = "14:00";     // Stop Time 2 (HH:MM)
input bool     InpUseSession3    = false;       // เปิดใช้งาน Session 3
input string   InpStart3         = "19:00";     // Start Time 3 (HH:MM)
input string   InpStop3          = "23:55";     // Stop Time 3 (HH:MM)

//--- [7] SYSTEM ---
input long     InpMagic          = 20260427;    // Magic Number

//--- Global Variables
int handle_ema;
int handle_atr;
int server_requests_today = 0;
int last_day = -1;
int last_week = -1;
bool daily_limit_hit = false;
datetime last_trade_time = 0; // Cooldown Tracker

double max_buy_profit_usd = 0;
double max_sell_profit_usd = 0;

//--- Drawdown Tracker Variables
double max_dd_day_pct = 0.0;
double max_dd_day_money = 0.0;
double max_dd_week_pct = 0.0;
double max_dd_week_money = 0.0;

// All Time Tracker Variables
double max_dd_all_time_pct = 0.0;
double max_dd_all_time_money = 0.0;
long   max_dd_all_time_date = 0; // เก็บเป็นวินาที (Unix timestamp) เพื่อง่ายต่อ Global Variable

string gv_all_pct = "";
string gv_all_money = "";
string gv_all_date = "";

//--- Daily Min/Max Profit Tracker
double max_profit_day_usd = 0.0;
double min_profit_day_usd = 0.0;
long   max_profit_date = 0;
long   min_profit_date = 0;

string gv_max_prof = "";
string gv_min_prof = "";
string gv_max_prof_date = "";
string gv_min_prof_date = "";

//--- Average Daily Profit Variables (Smart Cache)
datetime first_trade_time = 0;
double total_closed_profit = 0.0;
int last_history_deals = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   // --- ส่วนตรวจสอบวันหมดอายุ ---
   if (TimeCurrent() > InpExpiryDate)
     {
      Alert("Trial period expired! (หมดอายุการใช้งาน)");
      return(INIT_FAILED);
     }

   // --- ส่วนตรวจสอบเลขบัญชี (รองรับหลายบัญชี) ---
   bool isAllowed = false;
   int totalAccounts = ArraySize(AllowedAccounts);
   long currentAccount = AccountInfoInteger(ACCOUNT_LOGIN);

   for(int i=0; i < totalAccounts; i++)
     {
      if(currentAccount == AllowedAccounts[i] || AllowedAccounts[i] == 0)
        {
         isAllowed = true;
         break;
        }
     }

   if(!isAllowed)
     {
      Alert("เลขบัญชีไม่ถูกต้อง! EA นี้ไม่อนุญาตให้ใช้งานกับบัญชี: ", currentAccount);
      return(INIT_FAILED);
     }
   // =========================================================

   trade.SetExpertMagicNumber(InpMagic);
   trade.SetTypeFillingBySymbol(Symbol());

   // --- โหลดค่า All Time Max DD เดิม (ถ้ามี) ---
   gv_all_pct = "MAX_DD_PCT_" + IntegerToString(InpMagic) + "_" + Symbol();
   gv_all_money = "MAX_DD_MONEY_" + IntegerToString(InpMagic) + "_" + Symbol();
   gv_all_date = "MAX_DD_DATE_" + IntegerToString(InpMagic) + "_" + Symbol();

   if(GlobalVariableCheck(gv_all_pct)) max_dd_all_time_pct = GlobalVariableGet(gv_all_pct);
   if(GlobalVariableCheck(gv_all_money)) max_dd_all_time_money = GlobalVariableGet(gv_all_money);
   if(GlobalVariableCheck(gv_all_date)) max_dd_all_time_date = (long)GlobalVariableGet(gv_all_date);

   // --- โหลดค่ากำไรสูงสุด/ต่ำสุดของวัน เดิม (ถ้ามี) ---
   gv_max_prof = "MAX_PROF_USD_" + IntegerToString(InpMagic) + "_" + Symbol();
   gv_min_prof = "MIN_PROF_USD_" + IntegerToString(InpMagic) + "_" + Symbol();
   gv_max_prof_date = "MAX_PROF_DATE_" + IntegerToString(InpMagic) + "_" + Symbol();
   gv_min_prof_date = "MIN_PROF_DATE_" + IntegerToString(InpMagic) + "_" + Symbol();

   if(GlobalVariableCheck(gv_max_prof)) max_profit_day_usd = GlobalVariableGet(gv_max_prof);
   if(GlobalVariableCheck(gv_min_prof)) min_profit_day_usd = GlobalVariableGet(gv_min_prof);
   if(GlobalVariableCheck(gv_max_prof_date)) max_profit_date = (long)GlobalVariableGet(gv_max_prof_date);
   if(GlobalVariableCheck(gv_min_prof_date)) min_profit_date = (long)GlobalVariableGet(gv_min_prof_date);

   handle_ema = iMA(Symbol(), PERIOD_M15, 21, 0, MODE_EMA, PRICE_CLOSE);
   handle_atr = iATR(Symbol(), PERIOD_M30, 14);

   if(handle_ema == INVALID_HANDLE || handle_atr == INVALID_HANDLE)
     {
      Print("Error loading indicators");
      return(INIT_FAILED);
     }

   m_symbol.Name(Symbol());
   m_symbol.RefreshRates();

   //--- Set Auto Chart Candles Colors
   ChartSetInteger(0, CHART_MODE, CHART_CANDLES);
   ChartSetInteger(0, CHART_COLOR_CHART_UP, clrDeepSkyBlue);
   ChartSetInteger(0, CHART_COLOR_CHART_DOWN, clrRed);
   ChartSetInteger(0, CHART_COLOR_CANDLE_BULL, clrDeepSkyBlue);
   ChartSetInteger(0, CHART_COLOR_CANDLE_BEAR, clrRed);

   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   // Clear all EA dashboard labels when removed
   ObjectsDeleteAll(0, "lbl_");
  }

//+------------------------------------------------------------------+
//| Smart Volume Normalization                                       |
//+------------------------------------------------------------------+
double GetValidLot(double calculate_lot)
  {
   double step = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_STEP);
   double min_lot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MIN);
   double max_lot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MAX);
   
   if(step <= 0) step = 0.01; // Failsafe
   
   double valid_lot = MathRound(calculate_lot / step) * step;
   if(valid_lot < min_lot) valid_lot = min_lot;
   if(valid_lot > max_lot) valid_lot = max_lot;
   
   return NormalizeDouble(valid_lot, 2);
  }

//+------------------------------------------------------------------+
//| Order Sending Wrapper (Anti-Ban & Cooldown Logic)                |
//+------------------------------------------------------------------+
bool SendBuy(double lot, double price)
  {
   if(TimeCurrent() - last_trade_time < 3) return false; // 3 seconds Cooldown
   if(server_requests_today >= InpMaxServerReq) return false;
   
   server_requests_today++;
   last_trade_time = TimeCurrent(); 
   
   bool res = trade.Buy(lot, Symbol(), price);
   if(!res) Print("BUY Failed! Error Code: ", trade.ResultRetcode(), " | Check Margin/Lot");
   return res;
  }

bool SendSell(double lot, double price)
  {
   if(TimeCurrent() - last_trade_time < 3) return false; // 3 seconds Cooldown
   if(server_requests_today >= InpMaxServerReq) return false;
   
   server_requests_today++;
   last_trade_time = TimeCurrent();
   
   bool res = trade.Sell(lot, Symbol(), price);
   if(!res) Print("SELL Failed! Error Code: ", trade.ResultRetcode(), " | Check Margin/Lot");
   return res;
  }

bool SendClose(ulong ticket)
  {
   if(server_requests_today >= InpMaxServerReq) return false;
   server_requests_today++;
   
   bool res = trade.PositionClose(ticket);
   if(!res) Print("CLOSE Failed! Error Code: ", trade.ResultRetcode());
   return res;
  }

//+------------------------------------------------------------------+
//| Average & Daily Profit Calculation (Smart Cache)                 |
//+------------------------------------------------------------------+
void UpdateTotalProfit()
  {
   if(HistorySelect(0, TimeCurrent()))
     {
      int current_deals = HistoryDealsTotal();
      if(current_deals == last_history_deals) return; // ทำงานแค่ตอนมีประวัติใหม่เท่านั้น ลดการใช้ CPU

      total_closed_profit = 0.0;
      for(int i=0; i<current_deals; i++)
        {
         ulong ticket = HistoryDealGetTicket(i);
         if(HistoryDealGetInteger(ticket, DEAL_MAGIC) == InpMagic)
           {
            if(first_trade_time == 0) first_trade_time = (datetime)HistoryDealGetInteger(ticket, DEAL_TIME);
            total_closed_profit += HistoryDealGetDouble(ticket, DEAL_PROFIT);
            total_closed_profit += HistoryDealGetDouble(ticket, DEAL_SWAP);
            total_closed_profit += HistoryDealGetDouble(ticket, DEAL_COMMISSION);
           }
        }
      last_history_deals = current_deals;
     }
  }

double GetDailyClosedProfit()
  {
   double profit = 0;
   datetime start_of_day = iTime(Symbol(), PERIOD_D1, 0);
   if(HistorySelect(start_of_day, TimeCurrent()))
     {
      int deals = HistoryDealsTotal();
      for(int i=0; i<deals; i++)
        {
         ulong ticket = HistoryDealGetTicket(i);
         if(HistoryDealGetInteger(ticket, DEAL_MAGIC) == InpMagic)
           {
            profit += HistoryDealGetDouble(ticket, DEAL_PROFIT);
            profit += HistoryDealGetDouble(ticket, DEAL_SWAP);
            profit += HistoryDealGetDouble(ticket, DEAL_COMMISSION);
           }
        }
     }
   return profit;
  }

//+------------------------------------------------------------------+
//| Session Time Check                                               |
//+------------------------------------------------------------------+
bool CheckSession(string start, string stop, int current_min)
  {
   string s1[], s2[];
   StringSplit(start, ':', s1);
   StringSplit(stop, ':', s2);
   if(ArraySize(s1) != 2 || ArraySize(s2) != 2) return false;
   
   int m_start = (int)StringToInteger(s1[0])*60 + (int)StringToInteger(s1[1]);
   int m_stop  = (int)StringToInteger(s2[0])*60 + (int)StringToInteger(s2[1]);
   
   if(m_start < m_stop) return (current_min >= m_start && current_min <= m_stop);
   else return (current_min >= m_start || current_min <= m_stop);
  }

bool IsTradingTime()
  {
   if(!InpUseTimeFilter) return true;
   
   MqlDateTime tm;
   TimeCurrent(tm);
   int current_minutes = tm.hour * 60 + tm.min;
   
   if(InpUseSession1 && CheckSession(InpStart1, InpStop1, current_minutes)) return true;
   if(InpUseSession2 && CheckSession(InpStart2, InpStop2, current_minutes)) return true;
   if(InpUseSession3 && CheckSession(InpStart3, InpStop3, current_minutes)) return true;
   
   return false;
  }

//+------------------------------------------------------------------+
//| Dashboard Helper Function                                        |
//+------------------------------------------------------------------+
void CreateLabel(string name, string text, int x, int y, color clr, int font_size = 11, bool is_bold = true)
  {
   if(ObjectFind(0, name) < 0)
     {
      ObjectCreate(0, name, OBJ_LABEL, 0, 0, 0);
      ObjectSetInteger(0, name, OBJPROP_CORNER, CORNER_RIGHT_UPPER);
      ObjectSetInteger(0, name, OBJPROP_ANCHOR, ANCHOR_LEFT_UPPER); // Left align relative to right corner
     }
   ObjectSetString(0, name, OBJPROP_TEXT, text);
   ObjectSetInteger(0, name, OBJPROP_XDISTANCE, x);
   ObjectSetInteger(0, name, OBJPROP_YDISTANCE, y);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetString(0, name, OBJPROP_FONT, is_bold ? "Arial Bold" : "Arial");
   ObjectSetInteger(0, name, OBJPROP_FONTSIZE, font_size);
  }

void UpdateDashboard(double bal, double float_prof, double eq, int orders, double freemargin, int spread)
  {
   // ปรับขยับ x_val เพิ่มขึ้นจาก 280 เป็น 300 เพื่อเว้นระยะให้ข้อความยาวๆ ไม่ทับกัน
   int x_val = 300;   // Position for numbers
   int x_txt = 140;   // Position for text labels
   int y_start = 20;
   int step = 18;

   color profit_clr = (float_prof >= 0) ? clrLimeGreen : clrRed;
   string currency = AccountInfoString(ACCOUNT_CURRENCY);

   CreateLabel("lbl_title", "TRADING PA SNIPER", x_val, y_start, clrGold, 12, true);

   CreateLabel("lbl_v_bal", DoubleToString(bal, 2), x_val, y_start + step*1, clrWhite);
   CreateLabel("lbl_t_bal", "Balance", x_txt, y_start + step*1, clrWhite);

   CreateLabel("lbl_v_prof", DoubleToString(float_prof, 2), x_val, y_start + step*2, profit_clr);
   CreateLabel("lbl_t_prof", "Basket Profit", x_txt, y_start + step*2, clrWhite);

   CreateLabel("lbl_v_eq", DoubleToString(eq, 2), x_val, y_start + step*3, clrWhite);
   CreateLabel("lbl_t_eq", "Equity", x_txt, y_start + step*3, clrWhite);

   CreateLabel("lbl_v_ord", IntegerToString(orders), x_val, y_start + step*4, clrWhite);
   CreateLabel("lbl_t_ord", "Total Orders", x_txt, y_start + step*4, clrWhite);

   CreateLabel("lbl_v_fm", DoubleToString(freemargin, 2), x_val, y_start + step*5, clrYellow);
   CreateLabel("lbl_t_fm", "FreeMargin", x_txt, y_start + step*5, clrWhite);

   string ddd_txt = DoubleToString(max_dd_day_pct, 2) + "% / " + DoubleToString(max_dd_day_money, 2) + " " + currency;
   CreateLabel("lbl_v_ddd", ddd_txt, x_val, y_start + step*6, clrRed);
   CreateLabel("lbl_t_ddd", "MaxDD (Day)", x_txt, y_start + step*6, clrWhite);

   string ddw_txt = DoubleToString(max_dd_week_pct, 2) + "% / " + DoubleToString(max_dd_week_money, 2) + " " + currency;
   CreateLabel("lbl_v_ddw", ddw_txt, x_val, y_start + step*7, clrRed);
   CreateLabel("lbl_t_ddw", "MaxDD (Week)", x_txt, y_start + step*7, clrWhite);

   string dda_txt = DoubleToString(max_dd_all_time_pct, 2) + "% / " + DoubleToString(max_dd_all_time_money, 2) + " " + currency;
   CreateLabel("lbl_v_dda", dda_txt, x_val, y_start + step*8, clrRed);
   CreateLabel("lbl_t_dda", "MaxDD All Time", x_txt, y_start + step*8, clrWhite);

   // --- วันที่เกิด Max DD All Time วางบรรทัดถัดมา ---
   string date_str = "-";
   if(max_dd_all_time_date > 0)
     {
      date_str = TimeToString((datetime)max_dd_all_time_date, TIME_DATE);
     }
   CreateLabel("lbl_v_dda_d", "(Date: " + date_str + ")", x_val, y_start + step*9, clrLightCoral, 9, false);

   CreateLabel("lbl_v_sp", IntegerToString(spread), x_val, y_start + step*10, clrWhite);
   CreateLabel("lbl_t_sp", "Spread", x_txt, y_start + step*10, clrWhite);

   string cmds_txt = IntegerToString(server_requests_today) + " / " + IntegerToString(InpMaxServerReq);
   CreateLabel("lbl_v_cmd", cmds_txt, x_val, y_start + step*11, clrLightSkyBlue);
   CreateLabel("lbl_t_cmd", "Daily Cmds", x_txt, y_start + step*11, clrWhite);

   // --- Min/Max Daily Profit (แยกวันที่ลงมาอีกบรรทัดกันข้อความทับกัน) ---
   string max_p_date = (max_profit_date > 0) ? TimeToString((datetime)max_profit_date, TIME_DATE) : "-";
   string max_p_txt = DoubleToString(max_profit_day_usd, 2) + " " + currency;
   CreateLabel("lbl_v_maxp", max_p_txt, x_val, y_start + step*12, clrLimeGreen);
   CreateLabel("lbl_t_maxp", "Best Day Profit", x_txt, y_start + step*12, clrWhite);
   CreateLabel("lbl_v_maxp_d", "(Date: " + max_p_date + ")", x_val, y_start + step*13, clrLimeGreen, 9, false);

   string min_p_date = (min_profit_date > 0) ? TimeToString((datetime)min_profit_date, TIME_DATE) : "-";
   string min_p_txt = DoubleToString(min_profit_day_usd, 2) + " " + currency;
   CreateLabel("lbl_v_minp", min_p_txt, x_val, y_start + step*14, clrLightCoral);
   CreateLabel("lbl_t_minp", "Worst Day Profit", x_txt, y_start + step*14, clrWhite);
   CreateLabel("lbl_v_minp_d", "(Date: " + min_p_date + ")", x_val, y_start + step*15, clrLightCoral, 9, false);

   // --- ส่วนคำนวณค่าเฉลี่ยกำไรต่อวัน ---
   int days_run = 1; // เริ่มต้นที่ 1 วันป้องกันการหารด้วยศูนย์
   if(first_trade_time > 0)
     {
      days_run = (int)((TimeCurrent() - first_trade_time) / 86400); // 86400 วินาที = 1 วัน
      if(days_run < 1) days_run = 1;
     }
   double avg_daily_profit = total_closed_profit / days_run;

   string avg_p_txt = DoubleToString(avg_daily_profit, 2) + " " + currency;
   CreateLabel("lbl_v_avgp", avg_p_txt, x_val, y_start + step*16, clrTurquoise); // สีฟ้าน้ำทะเลเด่นๆ
   CreateLabel("lbl_t_avgp", "Avg Daily Profit", x_txt, y_start + step*16, clrWhite);

   // --- ส่วนแจ้งเตือน Soft Close บนหน้าจอ (ขยับบรรทัดลงมา) ---
   if(InpSoftClose)
     {
      CreateLabel("lbl_warn_sc1", "!!! SOFT CLOSE ACTIVE !!!", 240, y_start + step*18, clrMagenta, 11, true);
      CreateLabel("lbl_warn_sc2", "(รวบกำไรไม้ค้างแล้วจะหยุด)", 240, y_start + step*19, clrLightGray, 9, false);
     }
   else
     {
      ObjectDelete(0, "lbl_warn_sc1");
      ObjectDelete(0, "lbl_warn_sc2");
     }
  }

//+------------------------------------------------------------------+
//| Main Tick Logic                                                  |
//+------------------------------------------------------------------+
void OnTick()
  {
   m_symbol.RefreshRates();

   // --- Daily & Weekly Reset Check ---
   MqlDateTime dt;
   TimeCurrent(dt);
   
   if(dt.day != last_day)
     {
      last_day = dt.day;
      server_requests_today = 0;
      daily_limit_hit = false;
      max_dd_day_pct = 0.0;
      max_dd_day_money = 0.0;
     }
     
   int current_week = (int)(TimeCurrent() / 604800);
   if(current_week != last_week)
     {
      last_week = current_week;
      max_dd_week_pct = 0.0; 
      max_dd_week_money = 0.0;
     }

   if(server_requests_today >= InpMaxServerReq) return;

   // --- Update Drawdown Values ---
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double current_dd_money = 0.0;
   double current_dd_pct = 0.0;
   
   if(balance > 0 && equity < balance)
     {
      current_dd_money = balance - equity;
      current_dd_pct = (current_dd_money / balance) * 100.0;
     }
      
   if(current_dd_pct > max_dd_day_pct) 
     {
      max_dd_day_pct = current_dd_pct;
      max_dd_day_money = current_dd_money;
     }
   if(current_dd_pct > max_dd_week_pct) 
     {
      max_dd_week_pct = current_dd_pct;
      max_dd_week_money = current_dd_money;
     }
     
   // --- บันทึก Max DD All Time และบันทึกลง Global Variables ---
   if(current_dd_pct > max_dd_all_time_pct) 
     {
      max_dd_all_time_pct = current_dd_pct;
      max_dd_all_time_money = current_dd_money;
      max_dd_all_time_date = (long)TimeCurrent(); // เก็บวันที่เกิด DD

      GlobalVariableSet(gv_all_pct, max_dd_all_time_pct);
      GlobalVariableSet(gv_all_money, max_dd_all_time_money);
      GlobalVariableSet(gv_all_date, (double)max_dd_all_time_date);
     }

   // --- Safety Check: Drawdown (%) Limit ---
   if(current_dd_pct >= InpMaxDDPercent)
     {
      CloseAllPositions();
      Print("HARD STOP! Max DD Reached: ", DoubleToString(current_dd_pct, 2), "%");
      return;
     }

   // --- Logic Variables ---
   int buy_count = 0, sell_count = 0;
   double buy_profit = 0, sell_profit = 0;
   double buy_total_lot = 0, sell_total_lot = 0;
   double buy_total_cost = 0, sell_total_cost = 0;
   double last_buy_price = 0, last_sell_price = 0;
   double last_buy_lot = 0, last_sell_lot = 0;

   // 1. Scan Current Positions
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(m_position.SelectByIndex(i))
        {
         if(m_position.Symbol() == Symbol() && m_position.Magic() == InpMagic)
           {
            double pos_profit = m_position.Profit() + m_position.Swap() + m_position.Commission();
            double pos_cost = m_position.Volume() * m_position.PriceOpen();

            if(m_position.PositionType() == POSITION_TYPE_BUY)
              {
               buy_count++;
               buy_profit += pos_profit;
               buy_total_lot += m_position.Volume();
               buy_total_cost += pos_cost;
               if(last_buy_price == 0 || m_position.PriceOpen() < last_buy_price)
                 {
                  last_buy_price = m_position.PriceOpen();
                  last_buy_lot = m_position.Volume();
                 }
              }
            else if(m_position.PositionType() == POSITION_TYPE_SELL)
              {
               sell_count++;
               sell_profit += pos_profit;
               sell_total_lot += m_position.Volume();
               sell_total_cost += pos_cost;
               if(last_sell_price == 0 || m_position.PriceOpen() > last_sell_price)
                 {
                  last_sell_price = m_position.PriceOpen();
                  last_sell_lot = m_position.Volume();
                 }
              }
           }
        }
     }

   // Reset Trailing Trackers if no positions
   if(buy_count == 0) max_buy_profit_usd = 0;
   if(sell_count == 0) max_sell_profit_usd = 0;

   // --- Daily Targets & Limits ---
   double floating_profit = buy_profit + sell_profit;
   double daily_closed_profit = GetDailyClosedProfit();
   double total_daily_profit = daily_closed_profit + floating_profit;

   // --- บันทึกกำไรสูงสุดและต่ำสุดของวัน ---
   if(daily_closed_profit > max_profit_day_usd && daily_closed_profit > 0)
     {
      max_profit_day_usd = daily_closed_profit;
      max_profit_date = (long)TimeCurrent();
      GlobalVariableSet(gv_max_prof, max_profit_day_usd);
      GlobalVariableSet(gv_max_prof_date, (double)max_profit_date);
     }
   if(daily_closed_profit < min_profit_day_usd && daily_closed_profit < 0)
     {
      min_profit_day_usd = daily_closed_profit;
      min_profit_date = (long)TimeCurrent();
      GlobalVariableSet(gv_min_prof, min_profit_day_usd);
      GlobalVariableSet(gv_min_prof_date, (double)min_profit_date);
     }

   // --- เรียกฟังก์ชันอัปเดตกำไรสะสมก่อนอัปเดตหน้าจอ ---
   UpdateTotalProfit();

   // --- Update Visual Dashboard ---
   int total_orders = buy_count + sell_count;
   double free_margin = AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   int spread = (int)SymbolInfoInteger(Symbol(), SYMBOL_SPREAD);
   UpdateDashboard(balance, floating_profit, equity, total_orders, free_margin, spread);

   if(!daily_limit_hit)
     {
      if(InpDailyProfit > 0 && total_daily_profit >= InpDailyProfit)
        {
         CloseAllPositions();
         daily_limit_hit = true;
         Print("Daily Profit Target Reached!");
         return;
        }
      if(InpDailyLoss > 0 && total_daily_profit <= -InpDailyLoss)
        {
         CloseAllPositions();
         daily_limit_hit = true;
         Print("Daily Loss Limit Reached!");
         return;
        }
     }

   if(daily_limit_hit) return;

   // --- Exit Strategy (Close Logic) ---
   bool close_buy = false;
   bool close_sell = false;

   if(InpTargetUSD > 0 && buy_count > 0 && buy_profit >= InpTargetUSD) close_buy = true;
   if(InpTargetUSD > 0 && sell_count > 0 && sell_profit >= InpTargetUSD) close_sell = true;

   if(InpTPAverage > 0)
     {
      if(buy_count > 0 && buy_total_lot > 0)
        {
         double avg_buy_price = buy_total_cost / buy_total_lot;
         double point_profit = (m_symbol.Bid() - avg_buy_price) / m_symbol.Point();
         if(point_profit >= InpTPAverage) close_buy = true;
        }
      if(sell_count > 0 && sell_total_lot > 0)
        {
         double avg_sell_price = sell_total_cost / sell_total_lot;
         double point_profit = (avg_sell_price - m_symbol.Ask()) / m_symbol.Point();
         if(point_profit >= InpTPAverage) close_sell = true;
        }
     }

   if(InpTrailingStart > 0 && InpTrailingStop > 0)
     {
      if(buy_count > 0)
        {
         if(buy_profit > max_buy_profit_usd) max_buy_profit_usd = buy_profit;
         if(max_buy_profit_usd >= InpTrailingStart)
           {
            double lock_profit = max_buy_profit_usd - (InpTrailingStart - InpTrailingStop);
            if(buy_profit <= lock_profit) close_buy = true;
           }
        }
      if(sell_count > 0)
        {
         if(sell_profit > max_sell_profit_usd) max_sell_profit_usd = sell_profit;
         if(max_sell_profit_usd >= InpTrailingStart)
           {
            double lock_profit = max_sell_profit_usd - (InpTrailingStart - InpTrailingStop);
            if(sell_profit <= lock_profit) close_sell = true;
           }
        }
     }

   if(close_buy)  { ClosePositionsByType(POSITION_TYPE_BUY); buy_count = 0; max_buy_profit_usd = 0; }
   if(close_sell) { ClosePositionsByType(POSITION_TYPE_SELL); sell_count = 0; max_sell_profit_usd = 0; }

   // --- Entry & Grid Logic ---
   double grid_distance = InpPipStep * m_symbol.Point();
   
   if(InpUseATRGrid)
     {
      double atr[];
      CopyBuffer(handle_atr, 0, 0, 1, atr);
      double dynamic_step = (atr[0] / m_symbol.Point()) * InpATR_Mult;
      if(dynamic_step < InpMinStep) dynamic_step = InpMinStep;
      if(dynamic_step > InpMaxStep) dynamic_step = InpMaxStep;
      grid_distance = dynamic_step * m_symbol.Point();
     }

   // --- FIRST ORDER ---
   if(buy_count == 0 && sell_count == 0)
     {
      if(InpSoftClose) return; 
      if(!IsTradingTime()) return;

      double ema[];
      CopyBuffer(handle_ema, 0, 0, 1, ema);
      
      double safe_lot = GetValidLot(InpLotStart);
      if(m_symbol.Ask() > ema[0]) SendBuy(safe_lot, m_symbol.Ask());
      else if(m_symbol.Bid() < ema[0]) SendSell(safe_lot, m_symbol.Bid());
     }
   // --- GRID MARTINGALE ---
   else
     {
      if(buy_count > 0 && buy_count < InpMaxOrders)
        {
         if(m_symbol.Ask() <= last_buy_price - grid_distance)
           {
            double next_lot = GetValidLot(last_buy_lot * InpMultiplier);
            SendBuy(next_lot, m_symbol.Ask());
           }
        }
      if(sell_count > 0 && sell_count < InpMaxOrders)
        {
         if(m_symbol.Bid() >= last_sell_price + grid_distance)
           {
            double next_lot = GetValidLot(last_sell_lot * InpMultiplier);
            SendSell(next_lot, m_symbol.Bid());
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Custom Functions for Closing Positions                           |
//+------------------------------------------------------------------+
void CloseAllPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(m_position.SelectByIndex(i))
         if(m_position.Symbol() == Symbol() && m_position.Magic() == InpMagic)
            SendClose(m_position.Ticket());
     }
  }

void ClosePositionsByType(ENUM_POSITION_TYPE type)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(m_position.SelectByIndex(i))
         if(m_position.Symbol() == Symbol() && m_position.Magic() == InpMagic && m_position.PositionType() == type)
            SendClose(m_position.Ticket());
     }
  }
//+------------------------------------------------------------------+